title: EvoBioComp
description: Project Page for (proposed) NSF REU program in Intersecting Evolutionary Biology/Computation
theme: just-the-docs

url: https://efredericks.github.io/REU-Evolution-Computing/

aux_links:
  repo: https://github.com/efredericks/REU-Evolution-Computing 
